/**
 * layouts/contrast/index.js
 * Structurally distinct CONTRAST layouts.
 *
 * Contrast = this vs that, before/after, expected vs reality, irony.
 * Visual tension between two ideas. Duality is the point.
 * Single primary intent per layout.
 * Font sizes calibrated for 1080×1920 canvas.
 */

export default [

  // 1 — Diagonal split — two assets separated by diagonal cut + text each side
  {
    id: "DiagonalContrast",
    label: "Diagonal Contrast",
    intent: ["contrast"],
    energy: ["high"],
    orientation: ["9:16"],
    niche: ["entertainment", "sports", "gaming", "finance"],
    assetCount: 2, textCount: 2,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:0, y:0, width:60, height:100, zIndex:1, start:0, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ objectFit:"cover" } },
      { id:"z2", type:"asset", role:"secondary_asset", order:2, x:40, y:0, width:60, height:100, zIndex:1, start:0.15, end:null,
        enterAnimation:"slideLeftIn", exitAnimation:"none",
        style:{ objectFit:"cover" } },
      { id:"z3", type:"text", role:"headline", maxChars:12, order:1, x:3, y:38, width:36, height:24, zIndex:3, start:0.3, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:120, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"left", lineHeight:0.95,
          textShadow:"0 4px 20px rgba(0,0,0,0.95)" } },
      { id:"z4", type:"text", role:"subtext", maxChars:12, order:2, x:61, y:38, width:36, height:24, zIndex:3, start:0.45, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:120, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"right", lineHeight:0.95,
          textShadow:"0 4px 20px rgba(0,0,0,0.95)" } },
      { id:"z5", type:"decorative", role:"decorative", order:1, x:48, y:0, width:4, height:100, zIndex:4, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ opacity:1, borderRadius:0 } },
    ],
  },

  // 2 — Two card assets side by side + headline top + label under each card
  {
    id: "CardContrast",
    label: "Card Contrast",
    intent: ["contrast"],
    energy: ["medium"],
    orientation: ["9:16"],
    niche: ["education", "finance", "health", "lifestyle", "entertainment"],
    assetCount: 2, textCount: 3,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"text", role:"headline", maxChars:24, order:1, x:5, y:4, width:90, height:13, zIndex:4, start:0, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ fontSize:108, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      { id:"z2", type:"asset", role:"primary_asset", order:1, x:3, y:19, width:44, height:56, zIndex:1, start:0.2, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:16 } },
      { id:"z3", type:"asset", role:"secondary_asset", order:2, x:53, y:19, width:44, height:56, zIndex:1, start:0.35, end:null,
        enterAnimation:"slideLeftIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:16 } },
      { id:"z4", type:"text", role:"label", maxChars:14, order:2, x:3, y:77, width:44, height:10, zIndex:3, start:0.5, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:72, fontWeight:800, color:"#ffffff", textAlign:"center",
          lineHeight:1.0, textShadow:"0 2px 8px rgba(0,0,0,0.8)" } },
      { id:"z5", type:"text", role:"label", maxChars:14, order:3, x:53, y:77, width:44, height:10, zIndex:3, start:0.6, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:72, fontWeight:800, color:"#ffffff", textAlign:"center",
          lineHeight:1.0, textShadow:"0 2px 8px rgba(0,0,0,0.8)" } },
    ],
  },

  // 3 — Then vs Now stat contrast
  {
    id: "ThenNowContrast",
    label: "Then Now Contrast",
    intent: ["contrast"],
    energy: ["high"],
    orientation: ["9:16"],
    niche: ["finance", "education", "health", "sports", "tech"],
    assetCount: 0, textCount: 6,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"text", role:"headline", maxChars:24, order:1, x:5, y:4, width:90, height:10, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:700, color:"#ffffff", textAlign:"center",
          opacity:0.7, letterSpacing:"0.15em", textTransform:"uppercase" } },
      { id:"z2", type:"text", role:"label", maxChars:8, order:2, x:3, y:17, width:46, height:8, zIndex:2, start:0.2, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:600, color:"#ffffff", textAlign:"center",
          opacity:0.65, textTransform:"uppercase", letterSpacing:"0.12em" } },
      { id:"z3", type:"text", role:"label", maxChars:8, order:3, x:51, y:17, width:46, height:8, zIndex:2, start:0.2, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:600, color:"#ffffff", textAlign:"center",
          opacity:0.65, textTransform:"uppercase", letterSpacing:"0.12em" } },
      { id:"z4", type:"text", role:"stat", maxChars:8, order:4, x:3, y:26, width:46, height:32, zIndex:2, start:0.3, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ fontSize:160, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.9,
          letterSpacing:"-3px", opacity:0.5 } },
      { id:"z5", type:"text", role:"stat", maxChars:8, order:5, x:51, y:26, width:46, height:32, zIndex:2, start:0.5, end:null,
        enterAnimation:"slideLeftIn", exitAnimation:"none",
        style:{ fontSize:160, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.9,
          letterSpacing:"-3px" } },
      { id:"z6", type:"decorative", role:"decorative", order:1, x:48, y:18, width:4, height:40, zIndex:3, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ opacity:0.6, borderRadius:2 } },
      { id:"z7", type:"text", role:"subtext", maxChars:55, order:6, x:5, y:68, width:90, height:20, zIndex:2, start:0.7, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:68, fontWeight:700, color:"#ffffff", textAlign:"center",
          lineHeight:1.2, textShadow:"0 2px 12px rgba(0,0,0,0.8)" } },
    ],
  },

  // 4 — Stacked before/after assets full width + label badges on each
  {
    id: "BeforeAfterStackContrast",
    label: "Before After Stack Contrast",
    intent: ["contrast"],
    energy: ["high", "medium"],
    orientation: ["9:16"],
    niche: ["health", "lifestyle", "sports", "education", "finance"],
    assetCount: 2, textCount: 3,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:0, y:0, width:100, height:44, zIndex:1, start:0, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:0 } },
      { id:"z2", type:"text", role:"label", maxChars:10, order:1, x:4, y:2, width:30, height:8, zIndex:3, start:0.1, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:56, fontWeight:900, color:"#ffffff", textAlign:"center",
          background:"rgba(0,0,0,0.7)", borderRadius:8,
          letterSpacing:"0.08em", lineHeight:1.0 } },
      { id:"z3", type:"asset", role:"secondary_asset", order:2, x:0, y:56, width:100, height:44, zIndex:1, start:0.2, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:0 } },
      { id:"z4", type:"text", role:"label", maxChars:10, order:2, x:4, y:58, width:30, height:8, zIndex:3, start:0.3, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:56, fontWeight:900, color:"#ffffff", textAlign:"center",
          background:"rgba(0,0,0,0.7)", borderRadius:8,
          letterSpacing:"0.08em", lineHeight:1.0 } },
      { id:"z5", type:"text", role:"headline", maxChars:22, order:3, x:5, y:45, width:90, height:10, zIndex:4, start:0.4, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:96, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:1.0,
          textShadow:"0 4px 28px rgba(0,0,0,0.95)" } },
    ],
  },

  // 5 — Irony layout: large expectation text top + reality asset bottom + strikethrough feel
  {
    id: "IronyContrastHook",
    label: "Irony Contrast",
    intent: ["contrast"],
    energy: ["high"],
    orientation: ["9:16"],
    niche: ["entertainment", "gaming", "lifestyle", "education"],
    assetCount: 1, textCount: 3,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"text", role:"label", maxChars:16, order:1, x:5, y:4, width:90, height:7, zIndex:3, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:600, color:"#ffffff", textAlign:"center",
          letterSpacing:"0.15em", opacity:0.6, textTransform:"uppercase" } },
      { id:"z2", type:"text", role:"headline", maxChars:28, order:2, x:4, y:12, width:92, height:26, zIndex:3, start:0.2, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ fontSize:128, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.92,
          textShadow:"0 4px 28px rgba(0,0,0,0.9)",
          textDecoration:"line-through", opacity:0.5 } },
      { id:"z3", type:"asset", role:"primary_asset", order:1, x:0, y:40, width:100, height:52, zIndex:1, start:0.3, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:0 } },
      { id:"z4", type:"text", role:"subtext", maxChars:30, order:3, x:4, y:84, width:92, height:14, zIndex:3, start:0.5, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:96, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:1.0,
          textShadow:"0 4px 24px rgba(0,0,0,0.95)" } },
    ],
  },

  // 6 — Myth vs Fact: icon badge + bold claim + asset proof
  {
    id: "MythFactContrast",
    label: "Myth Fact Contrast",
    intent: ["contrast"],
    energy: ["high", "medium"],
    orientation: ["9:16"],
    niche: ["education", "health", "finance", "entertainment"],
    assetCount: 1, textCount: 3,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"text", role:"label", maxChars:8, order:1, x:4, y:4, width:40, height:9, zIndex:4, start:0, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:900, color:"#ffffff", textAlign:"center",
          background:"#ef4444", borderRadius:8,
          letterSpacing:"0.05em", lineHeight:1.0 } },
      { id:"z2", type:"text", role:"headline", maxChars:32, order:2, x:4, y:15, width:92, height:28, zIndex:3, start:0.2, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ fontSize:116, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"left", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      { id:"z3", type:"asset", role:"primary_asset", order:1, x:0, y:44, width:100, height:42, zIndex:1, start:0.3, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:0 } },
      { id:"z4", type:"text", role:"label", maxChars:8, order:3, x:4, y:46, width:36, height:9, zIndex:4, start:0.4, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:900, color:"#ffffff", textAlign:"center",
          background:"#22c55e", borderRadius:8,
          letterSpacing:"0.05em", lineHeight:1.0 } },
      { id:"z5", type:"text", role:"subtext", maxChars:45, order:4, x:4, y:88, width:92, height:10, zIndex:3, start:0.6, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:700, color:"#ffffff", textAlign:"center",
          lineHeight:1.2, textShadow:"0 2px 12px rgba(0,0,0,0.8)" } },
    ],
  },

  // 7 — Quote contrast: big italic expectation quote + full bleed asset + reality subtext
  {
    id: "QuoteRealityContrast",
    label: "Quote Reality Contrast",
    intent: ["contrast"],
    energy: ["medium"],
    orientation: ["9:16"],
    niche: ["lifestyle", "education", "entertainment", "health"],
    assetCount: 1, textCount: 2,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:0, y:0, width:100, height:100, zIndex:1, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:0 } },
      { id:"z2", type:"decorative", role:"decorative", order:1, x:0, y:0, width:100, height:55, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ background:"linear-gradient(180deg, rgba(0,0,0,0.88) 0%, transparent 100%)",
          opacity:1, borderRadius:0 } },
      { id:"z3", type:"decorative", role:"decorative", order:2, x:0, y:55, width:100, height:45, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ background:"linear-gradient(0deg, rgba(0,0,0,0.92) 0%, transparent 100%)",
          opacity:1, borderRadius:0 } },
      { id:"z4", type:"text", role:"quote", maxChars:60, order:1, x:6, y:6, width:88, height:40, zIndex:3, start:0.2, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:76, fontWeight:400, fontStyle:"italic",
          fontFamily:"'Playfair Display', serif",
          color:"#ffffff", textAlign:"center", lineHeight:1.35,
          textShadow:"0 2px 16px rgba(0,0,0,0.7)", opacity:0.6 } },
      { id:"z5", type:"text", role:"headline", maxChars:28, order:2, x:4, y:72, width:92, height:22, zIndex:3, start:0.5, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:120, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.95,
          textShadow:"0 4px 28px rgba(0,0,0,0.95)" } },
    ],
  },

  // 8 — Three column comparison: icon + label per column, no assets
  {
    id: "TripleColumnContrast",
    label: "Triple Column Contrast",
    intent: ["contrast"],
    energy: ["medium"],
    orientation: ["9:16"],
    niche: ["education", "finance", "health", "tech"],
    assetCount: 0, textCount: 7,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"text", role:"headline", maxChars:28, order:1, x:4, y:4, width:92, height:12, zIndex:3, start:0, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ fontSize:104, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      { id:"z2", type:"icon", role:"icon", order:1, x:4, y:22, width:28, height:16, zIndex:3, start:0.2, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        iconify:{ set:"ph", icon:"x-circle-fill" },
        style:{ opacity:1 } },
      { id:"z3", type:"icon", role:"icon", order:2, x:36, y:22, width:28, height:16, zIndex:3, start:0.3, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        iconify:{ set:"ph", icon:"minus-circle-fill" },
        style:{ opacity:1 } },
      { id:"z4", type:"icon", role:"icon", order:3, x:68, y:22, width:28, height:16, zIndex:3, start:0.4, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        iconify:{ set:"ph", icon:"check-circle-fill" },
        style:{ opacity:1 } },
      { id:"z5", type:"text", role:"label", maxChars:12, order:2, x:4, y:40, width:28, height:10, zIndex:3, start:0.3, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:800, color:"#ef4444", textAlign:"center", lineHeight:1.0 } },
      { id:"z6", type:"text", role:"label", maxChars:12, order:3, x:36, y:40, width:28, height:10, zIndex:3, start:0.4, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:800, color:"#f59e0b", textAlign:"center", lineHeight:1.0 } },
      { id:"z7", type:"text", role:"label", maxChars:12, order:4, x:68, y:40, width:28, height:10, zIndex:3, start:0.5, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:800, color:"#22c55e", textAlign:"center", lineHeight:1.0 } },
      { id:"z8", type:"text", role:"subtext", maxChars:55, order:5, x:4, y:60, width:92, height:20, zIndex:3, start:0.7, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:600, color:"#ffffff", textAlign:"center",
          lineHeight:1.25, textShadow:"0 2px 12px rgba(0,0,0,0.8)" } },
    ],
  },

];