/**
 * layouts/explanation/index.js
 * Structurally distinct EXPLANATION layouts.
 *
 * Explanation = how it works, why it matters, step by step, mechanism.
 * Clear, readable, informative. Teaching mode.
 * Single primary intent per layout.
 * Font sizes calibrated for 1080×1920 canvas.
 */

export default [

  // 1 — Big claim + supporting explanation paragraph
  {
    id: "ClaimExplain",
    label: "Claim Explain",
    intent: ["explanation"],
    energy: ["medium", "high"],
    orientation: ["9:16"],
    niche: ["education", "finance", "health", "tech", "lifestyle"],
    assetCount: 0, textCount: 3,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"text", role:"label", maxChars:15, order:1, x:5, y:6, width:90, height:8, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:600, color:"#ffffff", textAlign:"center",
          opacity:0.65, letterSpacing:"0.15em", textTransform:"uppercase" } },
      { id:"z2", type:"text", role:"headline", maxChars:30, order:2, x:3, y:17, width:94, height:30, zIndex:2, start:0.1, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:116, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      { id:"z3", type:"text", role:"subtext", maxChars:70, order:3, x:5, y:52, width:90, height:38, zIndex:2, start:0.4, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:500, color:"#ffffff", textAlign:"center",
          lineHeight:1.45, textShadow:"0 2px 8px rgba(0,0,0,0.7)" } },
    ],
  },

  // 2 — Asset left + explanation text right (side by side)
  {
    id: "AssetExplainSplit",
    label: "Asset Explain Split",
    intent: ["explanation"],
    energy: ["medium", "low"],
    orientation: ["9:16"],
    niche: ["education", "health", "tech", "finance", "lifestyle"],
    assetCount: 1, textCount: 3,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"text", role:"headline", maxChars:20, order:1, x:4, y:4, width:92, height:12, zIndex:3, start:0, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ fontSize:104, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      { id:"z2", type:"asset", role:"primary_asset", order:1, x:2, y:18, width:44, height:56, zIndex:1, start:0.2, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:14 } },
      { id:"z3", type:"text", role:"subtext", maxChars:55, order:2, x:50, y:20, width:46, height:30, zIndex:3, start:0.3, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:600, color:"#ffffff", textAlign:"left",
          lineHeight:1.35, textShadow:"0 2px 8px rgba(0,0,0,0.7)" } },
      { id:"z4", type:"text", role:"label", maxChars:25, order:3, x:50, y:54, width:46, height:16, zIndex:3, start:0.5, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:500, fontStyle:"italic",
          fontFamily:"'Playfair Display', serif",
          color:"#ffffff", textAlign:"left", lineHeight:1.3, opacity:0.8 } },
    ],
  },

  // 3 — Step by step: 3 steps with number + text row each
  {
    id: "StepByStepExplain",
    label: "Step By Step Explain",
    intent: ["explanation"],
    energy: ["medium"],
    orientation: ["9:16"],
    niche: ["education", "health", "finance", "tech", "lifestyle"],
    assetCount: 0, textCount: 7,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"text", role:"headline", maxChars:22, order:1, x:4, y:3, width:92, height:12, zIndex:3, start:0, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ fontSize:104, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      // Step 1
      { id:"z2", type:"text", role:"stat", maxChars:2, order:2, x:4, y:20, width:14, height:14, zIndex:3, start:0.2, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:120, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:1.0 } },
      { id:"z3", type:"text", role:"subtext", maxChars:40, order:3, x:22, y:22, width:74, height:10, zIndex:3, start:0.25, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:700, color:"#ffffff", textAlign:"left",
          lineHeight:1.15, textShadow:"0 2px 8px rgba(0,0,0,0.8)" } },
      { id:"z4", type:"decorative", role:"decorative", order:1, x:4, y:36, width:92, height:1, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ opacity:0.2, borderRadius:2 } },
      // Step 2
      { id:"z5", type:"text", role:"stat", maxChars:2, order:4, x:4, y:40, width:14, height:14, zIndex:3, start:0.45, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:120, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:1.0 } },
      { id:"z6", type:"text", role:"subtext", maxChars:40, order:5, x:22, y:42, width:74, height:10, zIndex:3, start:0.5, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:700, color:"#ffffff", textAlign:"left",
          lineHeight:1.15, textShadow:"0 2px 8px rgba(0,0,0,0.8)" } },
      { id:"z7", type:"decorative", role:"decorative", order:2, x:4, y:56, width:92, height:1, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ opacity:0.2, borderRadius:2 } },
      // Step 3
      { id:"z8", type:"text", role:"stat", maxChars:2, order:6, x:4, y:60, width:14, height:14, zIndex:3, start:0.7, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:120, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:1.0 } },
      { id:"z9", type:"text", role:"subtext", maxChars:40, order:7, x:22, y:62, width:74, height:10, zIndex:3, start:0.75, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:700, color:"#ffffff", textAlign:"left",
          lineHeight:1.15, textShadow:"0 2px 8px rgba(0,0,0,0.8)" } },
      { id:"z10", type:"text", role:"label", maxChars:40, order:8, x:4, y:80, width:92, height:12, zIndex:3, start:0.9, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:600, color:"#ffffff", textAlign:"center",
          background:"rgba(255,255,255,0.1)", borderRadius:10,
          lineHeight:1.2, letterSpacing:"0.05em" } },
    ],
  },

  // 4 — Full bleed asset + headline top + long explanation text bottom
  {
    id: "AssetExplainOverlay",
    label: "Asset Explain Overlay",
    intent: ["explanation"],
    energy: ["medium", "low"],
    orientation: ["9:16"],
    niche: ["education", "lifestyle", "travel", "food", "health"],
    assetCount: 1, textCount: 2,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:0, y:0, width:100, height:100, zIndex:1, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:0 } },
      { id:"z2", type:"decorative", role:"decorative", order:1, x:0, y:0, width:100, height:30, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ background:"linear-gradient(180deg, rgba(0,0,0,0.85) 0%, transparent 100%)",
          opacity:1, borderRadius:0 } },
      { id:"z3", type:"decorative", role:"decorative", order:2, x:0, y:50, width:100, height:50, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ background:"linear-gradient(0deg, rgba(0,0,0,0.92) 0%, transparent 100%)",
          opacity:1, borderRadius:0 } },
      { id:"z4", type:"text", role:"headline", maxChars:24, order:1, x:4, y:4, width:92, height:20, zIndex:3, start:0, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ fontSize:112, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"left", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      { id:"z5", type:"text", role:"subtext", maxChars:80, order:2, x:4, y:62, width:92, height:34, zIndex:3, start:0.4, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:500, color:"#ffffff", textAlign:"left",
          lineHeight:1.45, textShadow:"0 2px 8px rgba(0,0,0,0.8)" } },
    ],
  },

  // 5 — Two column data rows: icon + label left, value right
  {
    id: "DataRowsExplain",
    label: "Data Rows Explain",
    intent: ["explanation"],
    energy: ["medium", "low"],
    orientation: ["9:16"],
    niche: ["finance", "tech", "education", "health"],
    assetCount: 0, textCount: 7,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"text", role:"headline", maxChars:22, order:1, x:4, y:3, width:92, height:12, zIndex:3, start:0, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ fontSize:104, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"left", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      { id:"z2", type:"decorative", role:"decorative", order:1, x:4, y:17, width:92, height:1, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ opacity:0.3, borderRadius:2 } },
      // Row 1
      { id:"z3", type:"text", role:"label", maxChars:20, order:2, x:4, y:21, width:56, height:9, zIndex:3, start:0.2, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:600, color:"#ffffff", textAlign:"left",
          lineHeight:1.0, opacity:0.8 } },
      { id:"z4", type:"text", role:"stat", maxChars:10, order:3, x:62, y:21, width:34, height:9, zIndex:3, start:0.25, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:900, color:"#ffffff", textAlign:"right", lineHeight:1.0 } },
      { id:"z5", type:"decorative", role:"decorative", order:2, x:4, y:32, width:92, height:1, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ opacity:0.15, borderRadius:2 } },
      // Row 2
      { id:"z6", type:"text", role:"label", maxChars:20, order:4, x:4, y:36, width:56, height:9, zIndex:3, start:0.4, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:600, color:"#ffffff", textAlign:"left",
          lineHeight:1.0, opacity:0.8 } },
      { id:"z7", type:"text", role:"stat", maxChars:10, order:5, x:62, y:36, width:34, height:9, zIndex:3, start:0.45, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:900, color:"#ffffff", textAlign:"right", lineHeight:1.0 } },
      { id:"z8", type:"decorative", role:"decorative", order:3, x:4, y:47, width:92, height:1, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ opacity:0.15, borderRadius:2 } },
      // Row 3
      { id:"z9", type:"text", role:"label", maxChars:20, order:6, x:4, y:51, width:56, height:9, zIndex:3, start:0.6, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:600, color:"#ffffff", textAlign:"left",
          lineHeight:1.0, opacity:0.8 } },
      { id:"z10", type:"text", role:"stat", maxChars:10, order:7, x:62, y:51, width:34, height:9, zIndex:3, start:0.65, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:900, color:"#ffffff", textAlign:"right", lineHeight:1.0 } },
      { id:"z11", type:"decorative", role:"decorative", order:4, x:4, y:62, width:92, height:1, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ opacity:0.15, borderRadius:2 } },
      // Payoff subtext
      { id:"z12", type:"text", role:"subtext", maxChars:55, order:8, x:4, y:70, width:92, height:22, zIndex:3, start:0.8, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:600, color:"#ffffff", textAlign:"center",
          lineHeight:1.3, textShadow:"0 2px 12px rgba(0,0,0,0.8)" } },
    ],
  },

  // 6 — Icon grid 2x2 with labels — visual explanation of 4 concepts
  {
    id: "IconGridExplain",
    label: "Icon Grid Explain",
    intent: ["explanation"],
    energy: ["medium"],
    orientation: ["9:16"],
    niche: ["education", "health", "finance", "tech", "lifestyle"],
    assetCount: 0, textCount: 5,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"text", role:"headline", maxChars:22, order:1, x:4, y:3, width:92, height:12, zIndex:3, start:0, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ fontSize:104, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      // Top left
      { id:"z2", type:"icon", role:"icon", order:1, x:6, y:18, width:40, height:22, zIndex:3, start:0.2, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        iconify:{ set:"ph", icon:"lightbulb-fill" },
        style:{ opacity:1 } },
      { id:"z3", type:"text", role:"label", maxChars:14, order:2, x:6, y:41, width:40, height:8, zIndex:3, start:0.25, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:56, fontWeight:700, color:"#ffffff", textAlign:"center", lineHeight:1.0 } },
      // Top right
      { id:"z4", type:"icon", role:"icon", order:2, x:54, y:18, width:40, height:22, zIndex:3, start:0.35, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        iconify:{ set:"ph", icon:"chart-line-up-fill" },
        style:{ opacity:1 } },
      { id:"z5", type:"text", role:"label", maxChars:14, order:3, x:54, y:41, width:40, height:8, zIndex:3, start:0.4, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:56, fontWeight:700, color:"#ffffff", textAlign:"center", lineHeight:1.0 } },
      // Bottom left
      { id:"z6", type:"icon", role:"icon", order:3, x:6, y:53, width:40, height:22, zIndex:3, start:0.5, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        iconify:{ set:"ph", icon:"shield-check-fill" },
        style:{ opacity:1 } },
      { id:"z7", type:"text", role:"label", maxChars:14, order:4, x:6, y:76, width:40, height:8, zIndex:3, start:0.55, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:56, fontWeight:700, color:"#ffffff", textAlign:"center", lineHeight:1.0 } },
      // Bottom right
      { id:"z8", type:"icon", role:"icon", order:4, x:54, y:53, width:40, height:22, zIndex:3, start:0.65, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        iconify:{ set:"ph", icon:"clock-fill" },
        style:{ opacity:1 } },
      { id:"z9", type:"text", role:"label", maxChars:14, order:5, x:54, y:76, width:40, height:8, zIndex:3, start:0.7, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:56, fontWeight:700, color:"#ffffff", textAlign:"center", lineHeight:1.0 } },
      { id:"z10", type:"text", role:"subtext", maxChars:50, order:6, x:4, y:87, width:92, height:11, zIndex:3, start:0.85, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:600, color:"#ffffff", textAlign:"center",
          lineHeight:1.2, opacity:0.85 } },
    ],
  },

  // 7 — Cinematic explanation: full bleed asset + italic serif quote style explanation
  {
    id: "CinematicExplain",
    label: "Cinematic Explain",
    intent: ["explanation"],
    energy: ["low", "medium"],
    orientation: ["9:16"],
    niche: ["lifestyle", "travel", "education", "entertainment", "food"],
    assetCount: 1, textCount: 3,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:0, y:0, width:100, height:60, zIndex:1, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:0 } },
      { id:"z2", type:"decorative", role:"decorative", order:1, x:0, y:44, width:100, height:24, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ background:"linear-gradient(0deg, rgba(0,0,0,1) 0%, transparent 100%)",
          opacity:1, borderRadius:0 } },
      { id:"z3", type:"text", role:"label", maxChars:20, order:1, x:4, y:62, width:92, height:7, zIndex:3, start:0.2, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:48, fontWeight:600, color:"#ffffff", textAlign:"left",
          letterSpacing:"0.18em", opacity:0.6, textTransform:"uppercase" } },
      { id:"z4", type:"text", role:"headline", maxChars:28, order:2, x:4, y:70, width:92, height:16, zIndex:3, start:0.3, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:112, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"left", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      { id:"z5", type:"text", role:"subtext", maxChars:65, order:3, x:4, y:88, width:92, height:10, zIndex:3, start:0.5, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:400, fontStyle:"italic",
          fontFamily:"'Playfair Display', serif",
          color:"#ffffff", textAlign:"left", lineHeight:1.35, opacity:0.85 } },
    ],
  },

  // 8 — Minimal text-only: headline + long paragraph centered, no asset
  {
    id: "MinimalExplain",
    label: "Minimal Explain",
    intent: ["explanation"],
    energy: ["low"],
    orientation: ["9:16"],
    niche: ["finance", "education", "health", "tech"],
    assetCount: 0, textCount: 3,
    captionStrategy: "always",
    zones: [
      { id:"z1", type:"text", role:"label", maxChars:18, order:1, x:10, y:8, width:80, height:7, zIndex:3, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:48, fontWeight:600, color:"#ffffff", textAlign:"center",
          letterSpacing:"0.2em", opacity:0.55, textTransform:"uppercase" } },
      { id:"z2", type:"decorative", role:"decorative", order:1, x:38, y:17, width:24, height:1, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ opacity:0.4, borderRadius:2 } },
      { id:"z3", type:"text", role:"headline", maxChars:32, order:2, x:4, y:22, width:92, height:26, zIndex:3, start:0.2, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:120, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      { id:"z4", type:"text", role:"subtext", maxChars:80, order:3, x:6, y:54, width:88, height:38, zIndex:3, start:0.45, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:400, fontFamily:"'Outfit', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:1.5, opacity:0.9 } },
    ],
  },

];