/**
 * layouts/reveal/index.js
 * Structurally distinct REVEAL layouts.
 *
 * Reveal = payoff, aha moment, resolution, punchline.
 * High impact, clean, often minimal. The moment everything clicks.
 * Single primary intent per layout.
 * Font sizes calibrated for 1080×1920 canvas.
 */

export default [

  // 1 — Contained product/image + headline + subtext below
  {
    id: "ProductReveal",
    label: "Product Reveal",
    intent: ["reveal"],
    energy: ["medium"],
    orientation: ["9:16"],
    niche: ["lifestyle", "tech", "food", "health", "finance"],
    assetCount: 1, textCount: 2,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:8, y:4, width:84, height:56, zIndex:1, start:0, end:null,
        enterAnimation:"scaleIn", exitAnimation:"none",
        style:{ objectFit:"contain", borderRadius:20 } },
      { id:"z2", type:"text", role:"headline", maxChars:28, order:1, x:4, y:63, width:92, height:14, zIndex:3, start:0.35, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:120, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      { id:"z3", type:"text", role:"subtext", maxChars:50, order:2, x:5, y:80, width:90, height:16, zIndex:3, start:0.6, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:400, fontFamily:"'Outfit', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:1.35, opacity:0.85 } },
    ],
  },

  // 2 — Full bleed asset + giant centered reveal headline bottom
  {
    id: "FullBleedReveal",
    label: "Full Bleed Reveal",
    intent: ["reveal"],
    energy: ["high"],
    orientation: ["9:16"],
    niche: ["entertainment", "gaming", "sports", "travel", "lifestyle"],
    assetCount: 1, textCount: 2,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:0, y:0, width:100, height:100, zIndex:1, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:0 } },
      { id:"z2", type:"decorative", role:"decorative", order:1, x:0, y:55, width:100, height:45, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ background:"linear-gradient(0deg, rgba(0,0,0,0.95) 0%, transparent 100%)",
          opacity:1, borderRadius:0 } },
      { id:"z3", type:"text", role:"label", maxChars:18, order:1, x:4, y:66, width:92, height:7, zIndex:3, start:0.2, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:48, fontWeight:600, color:"#ffffff", textAlign:"center",
          letterSpacing:"0.18em", opacity:0.6, textTransform:"uppercase" } },
      { id:"z4", type:"text", role:"headline", maxChars:24, order:2, x:3, y:74, width:94, height:22, zIndex:3, start:0.4, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:148, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.9,
          textShadow:"0 6px 40px rgba(0,0,0,0.95)" } },
    ],
  },

  // 3 — Split reveal: dark left text side + asset right side
  {
    id: "SplitReveal",
    label: "Split Reveal",
    intent: ["reveal"],
    energy: ["medium", "high"],
    orientation: ["9:16"],
    niche: ["finance", "tech", "education", "lifestyle", "entertainment"],
    assetCount: 1, textCount: 3,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:48, y:0, width:52, height:100, zIndex:1, start:0, end:null,
        enterAnimation:"slideLeftIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:0 } },
      { id:"z2", type:"decorative", role:"decorative", order:1, x:40, y:0, width:20, height:100, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ background:"linear-gradient(90deg, rgba(0,0,0,1) 0%, transparent 100%)",
          opacity:1, borderRadius:0 } },
      { id:"z3", type:"text", role:"label", maxChars:16, order:1, x:3, y:8, width:50, height:7, zIndex:3, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:48, fontWeight:600, color:"#ffffff", textAlign:"left",
          letterSpacing:"0.15em", opacity:0.6, textTransform:"uppercase" } },
      { id:"z4", type:"text", role:"headline", maxChars:20, order:2, x:3, y:20, width:50, height:40, zIndex:3, start:0.3, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ fontSize:128, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"left", lineHeight:0.92,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      { id:"z5", type:"text", role:"subtext", maxChars:50, order:3, x:3, y:65, width:48, height:22, zIndex:3, start:0.55, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:500, fontFamily:"'Outfit', sans-serif",
          color:"#ffffff", textAlign:"left", lineHeight:1.4, opacity:0.85 } },
    ],
  },

  // 4 — Countdown reveal: label → subtext → giant headline popping in sequence
  {
    id: "SequenceReveal",
    label: "Sequence Reveal",
    intent: ["reveal"],
    energy: ["high"],
    orientation: ["9:16"],
    niche: ["entertainment", "gaming", "sports", "education", "finance"],
    assetCount: 0, textCount: 4,
    captionStrategy: "always",
    zones: [
      { id:"z1", type:"text", role:"label", maxChars:18, order:1, x:5, y:6, width:90, height:8, zIndex:3, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:600, color:"#ffffff", textAlign:"center",
          letterSpacing:"0.18em", opacity:0.55, textTransform:"uppercase" } },
      { id:"z2", type:"text", role:"tagline", maxChars:28, order:2, x:4, y:20, width:92, height:16, zIndex:3, start:0.3, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ fontSize:96, fontWeight:700, color:"#ffffff", textAlign:"center",
          lineHeight:1.05, opacity:0.7,
          textShadow:"0 2px 16px rgba(0,0,0,0.8)" } },
      { id:"z3", type:"text", role:"subtext", maxChars:22, order:3, x:3, y:40, width:94, height:20, zIndex:3, start:0.55, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:136, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.95,
          textShadow:"0 4px 32px rgba(0,0,0,0.9)" } },
      { id:"z4", type:"text", role:"headline", maxChars:18, order:4, x:2, y:64, width:96, height:24, zIndex:3, start:0.8, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:188, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.88,
          textShadow:"0 8px 48px rgba(0,0,0,0.95)" } },
    ],
  },

  // 5 — Arch asset + reveal text below with icon accent
  {
    id: "ArchReveal",
    label: "Arch Reveal",
    intent: ["reveal"],
    energy: ["medium", "high"],
    orientation: ["9:16"],
    niche: ["lifestyle", "entertainment", "travel", "health", "education"],
    assetCount: 1, textCount: 2,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:6, y:2, width:88, height:60, zIndex:1, start:0, end:null,
        enterAnimation:"scaleIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:"999px 999px 20px 20px" } },
      { id:"z2", type:"icon", role:"icon", order:1, x:42, y:60, width:16, height:10, zIndex:4, start:0.3, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        iconify:{ set:"ph", icon:"sparkle-fill" },
        style:{ opacity:1 } },
      { id:"z3", type:"text", role:"headline", maxChars:26, order:1, x:4, y:72, width:92, height:16, zIndex:3, start:0.45, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:120, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.95,
          textShadow:"0 4px 28px rgba(0,0,0,0.95)" } },
      { id:"z4", type:"text", role:"subtext", maxChars:48, order:2, x:5, y:90, width:90, height:8, zIndex:3, start:0.65, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:56, fontWeight:500, color:"#ffffff", textAlign:"center",
          lineHeight:1.3, opacity:0.8 } },
    ],
  },

  // 6 — Mosaic three asset reveal + headline strip bottom
  {
    id: "MosaicReveal",
    label: "Mosaic Reveal",
    intent: ["reveal"],
    energy: ["high", "medium"],
    orientation: ["9:16"],
    niche: ["entertainment", "lifestyle", "travel", "food", "sports"],
    assetCount: 3, textCount: 2,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:0, y:0, width:62, height:60, zIndex:1, start:0, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:0 } },
      { id:"z2", type:"asset", role:"secondary_asset", order:2, x:64, y:0, width:36, height:28, zIndex:1, start:0.2, end:null,
        enterAnimation:"slideLeftIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:0 } },
      { id:"z3", type:"asset", role:"asset_3", order:3, x:64, y:30, width:36, height:30, zIndex:1, start:0.35, end:null,
        enterAnimation:"slideLeftIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:0 } },
      { id:"z4", type:"text", role:"label", maxChars:20, order:1, x:4, y:62, width:92, height:8, zIndex:3, start:0.45, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:600, color:"#ffffff", textAlign:"center",
          letterSpacing:"0.15em", opacity:0.65, textTransform:"uppercase" } },
      { id:"z5", type:"text", role:"headline", maxChars:24, order:2, x:3, y:71, width:94, height:20, zIndex:3, start:0.6, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:144, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.92,
          textShadow:"0 6px 36px rgba(0,0,0,0.95)" } },
    ],
  },

  // 7 — Editorial reveal: italic serif headline + asset inset + supporting text
  {
    id: "EditorialReveal",
    label: "Editorial Reveal",
    intent: ["reveal"],
    energy: ["low", "medium"],
    orientation: ["9:16"],
    niche: ["lifestyle", "education", "food", "travel", "finance"],
    assetCount: 1, textCount: 3,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"text", role:"label", maxChars:16, order:1, x:4, y:4, width:92, height:7, zIndex:3, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:48, fontWeight:600, color:"#ffffff", textAlign:"left",
          letterSpacing:"0.2em", opacity:0.55, textTransform:"uppercase" } },
      { id:"z2", type:"text", role:"headline", maxChars:24, order:2, x:4, y:12, width:92, height:26, zIndex:3, start:0.15, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ fontSize:128, fontWeight:700, fontStyle:"italic",
          fontFamily:"'Playfair Display', serif",
          color:"#ffffff", textAlign:"left", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.8)" } },
      { id:"z3", type:"asset", role:"primary_asset", order:1, x:4, y:40, width:92, height:42, zIndex:1, start:0.35, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:16 } },
      { id:"z4", type:"text", role:"subtext", maxChars:55, order:3, x:4, y:85, width:92, height:12, zIndex:3, start:0.6, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:400, fontFamily:"'Outfit', sans-serif",
          color:"#ffffff", textAlign:"left", lineHeight:1.4, opacity:0.85 } },
    ],
  },

  // 8 — Dual asset reveal: two images side by side + giant headline bottom
  {
    id: "DualAssetReveal",
    label: "Dual Asset Reveal",
    intent: ["reveal"],
    energy: ["high", "medium"],
    orientation: ["9:16"],
    niche: ["entertainment", "sports", "gaming", "lifestyle", "travel"],
    assetCount: 2, textCount: 2,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:0, y:0, width:49, height:62, zIndex:1, start:0, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:0 } },
      { id:"z2", type:"asset", role:"secondary_asset", order:2, x:51, y:0, width:49, height:62, zIndex:1, start:0.2, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:0 } },
      { id:"z3", type:"decorative", role:"decorative", order:1, x:0, y:48, width:100, height:22, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ background:"linear-gradient(0deg, rgba(0,0,0,1) 0%, transparent 100%)",
          opacity:1, borderRadius:0 } },
      { id:"z4", type:"text", role:"label", maxChars:18, order:1, x:4, y:63, width:92, height:7, zIndex:3, start:0.3, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:48, fontWeight:600, color:"#ffffff", textAlign:"center",
          letterSpacing:"0.15em", opacity:0.6, textTransform:"uppercase" } },
      { id:"z5", type:"text", role:"headline", maxChars:22, order:2, x:3, y:71, width:94, height:24, zIndex:3, start:0.5, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:160, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.9,
          textShadow:"0 6px 40px rgba(0,0,0,0.95)" } },
    ],
  },

];