/**
 * layouts/stat/index.js
 * Structurally distinct STAT layouts.
 *
 * Stat = number-dominant, data point, metric, percentage.
 * The number IS the hero. Everything else supports it.
 * Single primary intent per layout.
 * Font sizes calibrated for 1080×1920 canvas.
 */

export default [

  // 1 — Asset top half + giant stat bottom half
  {
    id: "AssetStatBottom",
    label: "Asset Stat Bottom",
    intent: ["stat"],
    energy: ["medium", "high"],
    orientation: ["9:16"],
    niche: ["finance", "sports", "health", "education", "tech"],
    assetCount: 1, textCount: 3,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:0, y:0, width:100, height:46, zIndex:1, start:0, end:null,
        enterAnimation:"scaleIn", exitAnimation:"none",
        style:{ objectFit:"cover" } },
      { id:"z2", type:"text", role:"label", maxChars:20, order:1, x:4, y:49, width:92, height:7, zIndex:3, start:0.2, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:600, color:"#ffffff", textAlign:"center",
          letterSpacing:"0.15em", opacity:0.65, textTransform:"uppercase" } },
      { id:"z3", type:"text", role:"stat", maxChars:8, order:2, x:2, y:57, width:96, height:28, zIndex:3, start:0.35, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:220, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.9,
          letterSpacing:"-4px", textShadow:"0 8px 48px rgba(0,0,0,0.95)" } },
      { id:"z4", type:"text", role:"subtext", maxChars:45, order:3, x:5, y:88, width:90, height:10, zIndex:3, start:0.6, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:600, color:"#ffffff", textAlign:"center",
          lineHeight:1.2, textShadow:"0 2px 12px rgba(0,0,0,0.8)" } },
    ],
  },

  // 2 — Pure stat flood: number takes entire frame
  {
    id: "StatFlood",
    label: "Stat Flood",
    intent: ["stat"],
    energy: ["high"],
    orientation: ["9:16"],
    niche: ["finance", "sports", "education", "health", "tech", "gaming"],
    assetCount: 0, textCount: 3,
    captionStrategy: "always",
    zones: [
      { id:"z1", type:"text", role:"label", maxChars:18, order:1, x:4, y:5, width:92, height:7, zIndex:3, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:600, color:"#ffffff", textAlign:"center",
          letterSpacing:"0.18em", opacity:0.6, textTransform:"uppercase" } },
      { id:"z2", type:"text", role:"stat", maxChars:6, order:2, x:0, y:14, width:100, height:60, zIndex:3, start:0.2, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:320, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.88,
          textShadow:"0 12px 60px rgba(0,0,0,0.95)" } },
      { id:"z3", type:"text", role:"subtext", maxChars:50, order:3, x:4, y:80, width:92, height:16, zIndex:3, start:0.5, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:68, fontWeight:700, color:"#ffffff", textAlign:"center",
          lineHeight:1.2, textShadow:"0 2px 16px rgba(0,0,0,0.9)" } },
    ],
  },

  // 3 — Outlined stat: giant stroke-only number over full bleed asset
  {
    id: "OutlinedStat",
    label: "Outlined Stat",
    intent: ["stat"],
    energy: ["high"],
    orientation: ["9:16"],
    niche: ["gaming", "sports", "entertainment", "finance"],
    assetCount: 1, textCount: 3,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:0, y:0, width:100, height:100, zIndex:1, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:0 } },
      { id:"z2", type:"decorative", role:"decorative", order:1, x:0, y:0, width:100, height:100, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ background:"rgba(0,0,0,0.45)", opacity:1, borderRadius:0 } },
      { id:"z3", type:"text", role:"label", maxChars:18, order:1, x:4, y:5, width:92, height:7, zIndex:3, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:600, color:"#ffffff", textAlign:"center",
          letterSpacing:"0.18em", opacity:0.7, textTransform:"uppercase" } },
      { id:"z4", type:"text", role:"stat", maxChars:6, order:2, x:0, y:20, width:100, height:52, zIndex:3, start:0.3, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:300, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"transparent", textAlign:"center", lineHeight:0.88,
          WebkitTextStroke:"4px #ffffff" } },
      { id:"z5", type:"text", role:"subtext", maxChars:50, order:3, x:4, y:80, width:92, height:16, zIndex:3, start:0.6, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:68, fontWeight:700, color:"#ffffff", textAlign:"center",
          lineHeight:1.2, textShadow:"0 2px 16px rgba(0,0,0,0.9)" } },
    ],
  },

  // 4 — Dual stat: two giant numbers side by side + labels + headline
  {
    id: "DualStat",
    label: "Dual Stat",
    intent: ["stat"],
    energy: ["high", "medium"],
    orientation: ["9:16"],
    niche: ["finance", "sports", "health", "education", "tech"],
    assetCount: 0, textCount: 5,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"text", role:"headline", maxChars:24, order:1, x:4, y:4, width:92, height:12, zIndex:3, start:0, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ fontSize:104, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      { id:"z2", type:"decorative", role:"decorative", order:1, x:48, y:18, width:4, height:52, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ opacity:0.3, borderRadius:2 } },
      { id:"z3", type:"text", role:"stat", maxChars:6, order:2, x:2, y:18, width:44, height:36, zIndex:3, start:0.25, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ fontSize:200, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.9,
          textShadow:"0 6px 40px rgba(0,0,0,0.95)" } },
      { id:"z4", type:"text", role:"stat", maxChars:6, order:3, x:54, y:18, width:44, height:36, zIndex:3, start:0.45, end:null,
        enterAnimation:"slideLeftIn", exitAnimation:"none",
        style:{ fontSize:200, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.9,
          textShadow:"0 6px 40px rgba(0,0,0,0.95)" } },
      { id:"z5", type:"text", role:"label", maxChars:14, order:4, x:2, y:56, width:44, height:10, zIndex:3, start:0.35, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:56, fontWeight:600, color:"#ffffff", textAlign:"center",
          lineHeight:1.0, opacity:0.7 } },
      { id:"z6", type:"text", role:"label", maxChars:14, order:5, x:54, y:56, width:44, height:10, zIndex:3, start:0.55, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:56, fontWeight:600, color:"#ffffff", textAlign:"center",
          lineHeight:1.0, opacity:0.7 } },
      { id:"z7", type:"text", role:"subtext", maxChars:50, order:6, x:4, y:74, width:92, height:18, zIndex:3, start:0.7, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:600, color:"#ffffff", textAlign:"center",
          lineHeight:1.25, textShadow:"0 2px 12px rgba(0,0,0,0.8)" } },
    ],
  },

  // 5 — Stat with asset inset: giant number + small inset asset beside it
  {
    id: "StatAssetInset",
    label: "Stat Asset Inset",
    intent: ["stat"],
    energy: ["high", "medium"],
    orientation: ["9:16"],
    niche: ["finance", "sports", "health", "tech", "education"],
    assetCount: 1, textCount: 3,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"text", role:"label", maxChars:18, order:1, x:4, y:5, width:92, height:7, zIndex:3, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:600, color:"#ffffff", textAlign:"left",
          letterSpacing:"0.15em", opacity:0.65, textTransform:"uppercase" } },
      { id:"z2", type:"text", role:"stat", maxChars:6, order:2, x:2, y:14, width:62, height:44, zIndex:3, start:0.25, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:260, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"left", lineHeight:0.88,
          textShadow:"0 8px 48px rgba(0,0,0,0.95)" } },
      { id:"z3", type:"asset", role:"primary_asset", order:1, x:64, y:16, width:32, height:40, zIndex:2, start:0.3, end:null,
        enterAnimation:"slideLeftIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:14 } },
      { id:"z4", type:"text", role:"subtext", maxChars:55, order:3, x:4, y:65, width:92, height:26, zIndex:3, start:0.55, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:68, fontWeight:700, color:"#ffffff", textAlign:"left",
          lineHeight:1.25, textShadow:"0 2px 16px rgba(0,0,0,0.9)" } },
    ],
  },

  // 6 — Editorial stat: large italic context text + giant number + small label
  {
    id: "EditorialStat",
    label: "Editorial Stat",
    intent: ["stat"],
    energy: ["medium"],
    orientation: ["9:16"],
    niche: ["finance", "education", "health", "lifestyle", "tech"],
    assetCount: 0, textCount: 4,
    captionStrategy: "always",
    zones: [
      { id:"z1", type:"text", role:"label", maxChars:16, order:1, x:4, y:5, width:92, height:7, zIndex:3, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:48, fontWeight:600, color:"#ffffff", textAlign:"left",
          letterSpacing:"0.2em", opacity:0.55, textTransform:"uppercase" } },
      { id:"z2", type:"text", role:"subtext", maxChars:40, order:2, x:4, y:14, width:92, height:22, zIndex:3, start:0.2, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ fontSize:80, fontWeight:400, fontStyle:"italic",
          fontFamily:"'Playfair Display', serif",
          color:"#ffffff", textAlign:"left", lineHeight:1.15, opacity:0.75,
          textShadow:"0 2px 12px rgba(0,0,0,0.7)" } },
      { id:"z3", type:"text", role:"stat", maxChars:8, order:3, x:2, y:38, width:96, height:42, zIndex:3, start:0.4, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:280, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.88,
          textShadow:"0 10px 56px rgba(0,0,0,0.95)" } },
      { id:"z4", type:"text", role:"tagline", maxChars:30, order:4, x:4, y:83, width:92, height:12, zIndex:3, start:0.65, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:68, fontWeight:700, color:"#ffffff", textAlign:"center",
          lineHeight:1.2, textShadow:"0 2px 12px rgba(0,0,0,0.8)" } },
    ],
  },

  // 7 — Stat card: contained card with stat inside over background
  {
    id: "StatCard",
    label: "Stat Card",
    intent: ["stat"],
    energy: ["medium"],
    orientation: ["9:16"],
    niche: ["finance", "tech", "education", "health"],
    assetCount: 0, textCount: 4,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"text", role:"headline", maxChars:22, order:1, x:4, y:4, width:92, height:12, zIndex:3, start:0, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ fontSize:104, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      { id:"z2", type:"decorative", role:"decorative", order:1, x:6, y:18, width:88, height:56, zIndex:2, start:0.1, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ borderRadius:24, opacity:0.15,
          background:"rgba(255,255,255,1)" } },
      { id:"z3", type:"text", role:"label", maxChars:18, order:2, x:10, y:22, width:80, height:7, zIndex:3, start:0.2, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:48, fontWeight:600, color:"#ffffff", textAlign:"center",
          letterSpacing:"0.15em", opacity:0.7, textTransform:"uppercase" } },
      { id:"z4", type:"text", role:"stat", maxChars:8, order:3, x:8, y:30, width:84, height:34, zIndex:3, start:0.35, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:240, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.9,
          textShadow:"0 8px 48px rgba(0,0,0,0.95)" } },
      { id:"z5", type:"text", role:"subtext", maxChars:50, order:4, x:4, y:80, width:92, height:16, zIndex:3, start:0.6, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:600, color:"#ffffff", textAlign:"center",
          lineHeight:1.25, textShadow:"0 2px 12px rgba(0,0,0,0.8)" } },
    ],
  },

  // 8 — Stat with icon accent + asset background + bold context
  {
    id: "IconAccentStat",
    label: "Icon Accent Stat",
    intent: ["stat"],
    energy: ["high", "medium"],
    orientation: ["9:16"],
    niche: ["finance", "sports", "health", "gaming", "tech"],
    assetCount: 1, textCount: 3,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:0, y:0, width:100, height:100, zIndex:1, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:0 } },
      { id:"z2", type:"decorative", role:"decorative", order:1, x:0, y:0, width:100, height:100, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ background:"linear-gradient(180deg, rgba(0,0,0,0.55) 0%, rgba(0,0,0,0.88) 100%)",
          opacity:1, borderRadius:0 } },
      { id:"z3", type:"icon", role:"icon", order:1, x:40, y:6, width:20, height:13, zIndex:4, start:0, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        iconify:{ set:"ph", icon:"trend-up-bold" },
        style:{ opacity:1 } },
      { id:"z4", type:"text", role:"stat", maxChars:8, order:1, x:2, y:22, width:96, height:44, zIndex:3, start:0.25, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:280, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.88,
          textShadow:"0 10px 56px rgba(0,0,0,0.95)" } },
      { id:"z5", type:"text", role:"label", maxChars:20, order:2, x:4, y:68, width:92, height:8, zIndex:3, start:0.45, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:56, fontWeight:600, color:"#ffffff", textAlign:"center",
          letterSpacing:"0.12em", opacity:0.7, textTransform:"uppercase" } },
      { id:"z6", type:"text", role:"subtext", maxChars:50, order:3, x:4, y:80, width:92, height:16, zIndex:3, start:0.6, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:700, color:"#ffffff", textAlign:"center",
          lineHeight:1.25, textShadow:"0 2px 16px rgba(0,0,0,0.9)" } },
    ],
  },

];