/**
 * layouts/testimonial/index.js
 * Structurally distinct TESTIMONIAL layouts.
 *
 * Testimonial = social proof, review, quote, real person, trust.
 * Human, warm, credible. The viewer should believe and relate.
 * Single primary intent per layout.
 * Font sizes calibrated for 1080×1920 canvas.
 */

export default [

  // 1 — Full bleed person + overlaid quote
  {
    id: "FullBleedTestimonial",
    label: "Full Bleed Testimonial",
    intent: ["testimonial"],
    energy: ["medium", "high"],
    orientation: ["9:16"],
    niche: ["lifestyle", "health", "education", "finance", "entertainment"],
    assetCount: 1, textCount: 2,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:0, y:0, width:100, height:100, zIndex:1, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ objectFit:"cover" } },
      { id:"z2", type:"decorative", role:"decorative", order:1, x:0, y:42, width:100, height:58, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ background:"linear-gradient(0deg, rgba(0,0,0,0.95) 0%, transparent 100%)",
          opacity:1, borderRadius:0 } },
      { id:"z3", type:"text", role:"quote", maxChars:80, order:1, x:5, y:50, width:90, height:32, zIndex:3, start:0.3, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:72, fontWeight:700, fontStyle:"italic",
          fontFamily:"'Playfair Display', serif",
          color:"#ffffff", textAlign:"left", lineHeight:1.3,
          textShadow:"0 2px 16px rgba(0,0,0,0.9)" } },
      { id:"z4", type:"text", role:"subtext", maxChars:30, order:2, x:5, y:86, width:90, height:9, zIndex:3, start:0.6, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:56, fontWeight:600, color:"#ffffff", textAlign:"left",
          textShadow:"0 2px 8px rgba(0,0,0,0.8)", opacity:0.85 } },
    ],
  },

  // 2 — Star rating + quote + name (review card style)
  {
    id: "ReviewCard",
    label: "Review Card",
    intent: ["testimonial"],
    energy: ["medium"],
    orientation: ["9:16"],
    niche: ["lifestyle", "health", "food", "education", "finance"],
    assetCount: 0, textCount: 4,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"icon", role:"icon", order:1, x:25, y:8, width:50, height:12, zIndex:3, start:0, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        iconify:{ set:"ph", icon:"star-fill" },
        style:{ opacity:1 } },
      { id:"z2", type:"text", role:"quote", maxChars:90, order:2, x:5, y:24, width:90, height:46, zIndex:2, start:0.2, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:72, fontWeight:600, fontStyle:"italic",
          fontFamily:"'Playfair Display', serif",
          color:"#ffffff", textAlign:"center", lineHeight:1.35 } },
      { id:"z3", type:"text", role:"headline", maxChars:25, order:3, x:5, y:74, width:90, height:11, zIndex:2, start:0.5, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:72, fontWeight:700, color:"#ffffff", textAlign:"center",
          lineHeight:1.0, textShadow:"0 2px 8px rgba(0,0,0,0.8)" } },
      { id:"z4", type:"text", role:"subtext", maxChars:30, order:4, x:5, y:87, width:90, height:9, zIndex:2, start:0.7, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:400, color:"#ffffff", textAlign:"center",
          opacity:0.65, letterSpacing:"0.08em" } },
    ],
  },

  // 3 — Before/after: two assets + result quote + name
  {
    id: "BeforeAfterTestimonial",
    label: "Before After Testimonial",
    intent: ["testimonial"],
    energy: ["medium", "high"],
    orientation: ["9:16"],
    niche: ["health", "lifestyle", "fitness", "education", "finance"],
    assetCount: 2, textCount: 2,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:1, y:4, width:47, height:58, zIndex:1, start:0, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:14 } },
      { id:"z2", type:"text", role:"label", maxChars:10, order:1, x:2, y:6, width:22, height:7, zIndex:3, start:0.1, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:900, color:"#ffffff", textAlign:"center",
          background:"rgba(0,0,0,0.65)", borderRadius:6, lineHeight:1.0 } },
      { id:"z3", type:"asset", role:"secondary_asset", order:2, x:52, y:4, width:47, height:58, zIndex:1, start:0.2, end:null,
        enterAnimation:"slideLeftIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:14 } },
      { id:"z4", type:"text", role:"label", maxChars:10, order:2, x:53, y:6, width:22, height:7, zIndex:3, start:0.25, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:900, color:"#ffffff", textAlign:"center",
          background:"rgba(0,0,0,0.65)", borderRadius:6, lineHeight:1.0 } },
      { id:"z5", type:"text", role:"quote", maxChars:65, order:3, x:4, y:65, width:92, height:20, zIndex:3, start:0.4, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:68, fontWeight:700, fontStyle:"italic",
          fontFamily:"'Playfair Display', serif",
          color:"#ffffff", textAlign:"center", lineHeight:1.3,
          textShadow:"0 2px 12px rgba(0,0,0,0.8)" } },
      { id:"z6", type:"text", role:"subtext", maxChars:30, order:4, x:5, y:88, width:90, height:9, zIndex:3, start:0.65, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:56, fontWeight:600, color:"#ffffff", textAlign:"center",
          opacity:0.8, letterSpacing:"0.05em" } },
    ],
  },

  // 4 — Person inset top-right + large quote left + supporting text + name
  {
    id: "InsetPersonQuote",
    label: "Inset Person Quote",
    intent: ["testimonial"],
    energy: ["low", "medium"],
    orientation: ["9:16"],
    niche: ["lifestyle", "health", "education", "finance", "entertainment"],
    assetCount: 1, textCount: 3,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:62, y:4, width:34, height:26, zIndex:2, start:0, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:999 } },
      { id:"z2", type:"decorative", role:"decorative", order:1, x:58, y:2, width:42, height:30, zIndex:3, start:0, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ borderRadius:999, opacity:1 } },
      { id:"z3", type:"text", role:"quote", maxChars:45, order:1, x:4, y:8, width:56, height:24, zIndex:3, start:0.2, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ fontSize:80, fontWeight:700, fontStyle:"italic",
          fontFamily:"'Playfair Display', serif",
          color:"#ffffff", textAlign:"left", lineHeight:1.2,
          textShadow:"0 2px 12px rgba(0,0,0,0.8)" } },
      { id:"z4", type:"text", role:"subtext", maxChars:70, order:2, x:4, y:38, width:92, height:40, zIndex:3, start:0.4, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:500, color:"#ffffff", textAlign:"left",
          lineHeight:1.4, opacity:0.9 } },
      { id:"z5", type:"text", role:"label", maxChars:30, order:3, x:4, y:88, width:92, height:9, zIndex:3, start:0.65, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:56, fontWeight:600, color:"#ffffff", textAlign:"left",
          opacity:0.7, letterSpacing:"0.06em" } },
    ],
  },

  // 5 — Quote card: semi-transparent card + large quote + stars + name
  {
    id: "QuoteCardTestimonial",
    label: "Quote Card Testimonial",
    intent: ["testimonial"],
    energy: ["medium", "low"],
    orientation: ["9:16"],
    niche: ["lifestyle", "health", "education", "finance", "food"],
    assetCount: 1, textCount: 3,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:0, y:0, width:100, height:100, zIndex:1, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:0 } },
      { id:"z2", type:"decorative", role:"decorative", order:1, x:0, y:0, width:100, height:100, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ background:"rgba(0,0,0,0.55)", opacity:1, borderRadius:0 } },
      { id:"z3", type:"decorative", role:"decorative", order:2, x:5, y:20, width:90, height:62, zIndex:3, start:0.1, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ background:"rgba(255,255,255,0.08)", borderRadius:20,
          outline:"1px solid rgba(255,255,255,0.15)", opacity:1 } },
      { id:"z4", type:"icon", role:"icon", order:1, x:30, y:24, width:40, height:10, zIndex:4, start:0.2, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        iconify:{ set:"ph", icon:"star-fill" },
        style:{ opacity:1 } },
      { id:"z5", type:"text", role:"quote", maxChars:85, order:1, x:8, y:37, width:84, height:34, zIndex:4, start:0.35, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:500, fontStyle:"italic",
          fontFamily:"'Playfair Display', serif",
          color:"#ffffff", textAlign:"center", lineHeight:1.4 } },
      { id:"z6", type:"text", role:"headline", maxChars:22, order:2, x:8, y:73, width:84, height:8, zIndex:4, start:0.6, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:700, color:"#ffffff", textAlign:"center",
          lineHeight:1.0, letterSpacing:"0.04em" } },
      { id:"z7", type:"text", role:"label", maxChars:25, order:3, x:8, y:83, width:84, height:7, zIndex:4, start:0.75, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:48, fontWeight:400, color:"#ffffff", textAlign:"center",
          opacity:0.6, letterSpacing:"0.1em" } },
    ],
  },

  // 6 — Split testimonial: asset left half + quote right half
  {
    id: "SplitTestimonial",
    label: "Split Testimonial",
    intent: ["testimonial"],
    energy: ["medium"],
    orientation: ["9:16"],
    niche: ["lifestyle", "health", "education", "finance", "entertainment"],
    assetCount: 1, textCount: 3,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:0, y:0, width:46, height:100, zIndex:1, start:0, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:0 } },
      { id:"z2", type:"decorative", role:"decorative", order:1, x:38, y:0, width:16, height:100, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ background:"linear-gradient(90deg, rgba(0,0,0,1) 0%, transparent 100%)",
          opacity:1, borderRadius:0 } },
      { id:"z3", type:"icon", role:"icon", order:1, x:50, y:6, width:36, height:10, zIndex:3, start:0.1, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        iconify:{ set:"ph", icon:"star-fill" },
        style:{ opacity:1 } },
      { id:"z4", type:"text", role:"quote", maxChars:60, order:1, x:50, y:20, width:46, height:44, zIndex:3, start:0.25, end:null,
        enterAnimation:"slideLeftIn", exitAnimation:"none",
        style:{ fontSize:68, fontWeight:600, fontStyle:"italic",
          fontFamily:"'Playfair Display', serif",
          color:"#ffffff", textAlign:"left", lineHeight:1.35,
          textShadow:"0 2px 12px rgba(0,0,0,0.8)" } },
      { id:"z5", type:"text", role:"headline", maxChars:20, order:2, x:50, y:68, width:46, height:10, zIndex:3, start:0.5, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:700, color:"#ffffff", textAlign:"left",
          lineHeight:1.0, textShadow:"0 2px 8px rgba(0,0,0,0.8)" } },
      { id:"z6", type:"text", role:"label", maxChars:22, order:3, x:50, y:80, width:46, height:8, zIndex:3, start:0.65, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:48, fontWeight:400, color:"#ffffff", textAlign:"left",
          opacity:0.65, letterSpacing:"0.08em" } },
    ],
  },

  // 7 — Minimal quote: no asset, large centered italic quote + thin rule + name
  {
    id: "MinimalQuoteTestimonial",
    label: "Minimal Quote Testimonial",
    intent: ["testimonial"],
    energy: ["low"],
    orientation: ["9:16"],
    niche: ["lifestyle", "health", "education", "finance", "food"],
    assetCount: 0, textCount: 3,
    captionStrategy: "always",
    zones: [
      { id:"z1", type:"text", role:"label", maxChars:16, order:1, x:10, y:6, width:80, height:7, zIndex:3, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:48, fontWeight:600, color:"#ffffff", textAlign:"center",
          letterSpacing:"0.2em", opacity:0.5, textTransform:"uppercase" } },
      { id:"z2", type:"decorative", role:"decorative", order:1, x:38, y:15, width:24, height:1, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ opacity:0.35, borderRadius:2 } },
      { id:"z3", type:"text", role:"quote", maxChars:90, order:2, x:6, y:20, width:88, height:52, zIndex:3, start:0.2, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:72, fontWeight:400, fontStyle:"italic",
          fontFamily:"'Cormorant Garamond', serif",
          color:"#ffffff", textAlign:"center", lineHeight:1.45,
          textShadow:"0 2px 8px rgba(0,0,0,0.5)" } },
      { id:"z4", type:"decorative", role:"decorative", order:2, x:38, y:74, width:24, height:1, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ opacity:0.35, borderRadius:2 } },
      { id:"z5", type:"text", role:"headline", maxChars:25, order:3, x:6, y:78, width:88, height:10, zIndex:3, start:0.5, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:600, color:"#ffffff", textAlign:"center",
          lineHeight:1.0, letterSpacing:"0.06em" } },
      { id:"z6", type:"text", role:"subtext", maxChars:22, order:4, x:6, y:90, width:88, height:8, zIndex:3, start:0.65, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:48, fontWeight:400, color:"#ffffff", textAlign:"center",
          opacity:0.55, letterSpacing:"0.12em" } },
    ],
  },

  // 8 — Three quote cards stacked: small asset circles + short quotes
  {
    id: "StackedMiniTestimonials",
    label: "Stacked Mini Testimonials",
    intent: ["testimonial"],
    energy: ["medium"],
    orientation: ["9:16"],
    niche: ["lifestyle", "health", "education", "finance", "food"],
    assetCount: 3, textCount: 4,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"text", role:"headline", maxChars:22, order:1, x:4, y:3, width:92, height:11, zIndex:3, start:0, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ fontSize:100, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      // Card 1
      { id:"z2", type:"asset", role:"primary_asset", order:1, x:4, y:17, width:16, height:12, zIndex:2, start:0.2, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:999 } },
      { id:"z3", type:"text", role:"quote", maxChars:45, order:2, x:23, y:17, width:73, height:12, zIndex:3, start:0.25, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ fontSize:56, fontWeight:500, fontStyle:"italic",
          fontFamily:"'Playfair Display', serif",
          color:"#ffffff", textAlign:"left", lineHeight:1.3,
          background:"rgba(255,255,255,0.07)", borderRadius:10 } },
      // Card 2
      { id:"z4", type:"asset", role:"secondary_asset", order:2, x:4, y:33, width:16, height:12, zIndex:2, start:0.4, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:999 } },
      { id:"z5", type:"text", role:"quote", maxChars:45, order:3, x:23, y:33, width:73, height:12, zIndex:3, start:0.45, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ fontSize:56, fontWeight:500, fontStyle:"italic",
          fontFamily:"'Playfair Display', serif",
          color:"#ffffff", textAlign:"left", lineHeight:1.3,
          background:"rgba(255,255,255,0.07)", borderRadius:10 } },
      // Card 3
      { id:"z6", type:"asset", role:"asset_3", order:3, x:4, y:49, width:16, height:12, zIndex:2, start:0.6, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:999 } },
      { id:"z7", type:"text", role:"quote", maxChars:45, order:4, x:23, y:49, width:73, height:12, zIndex:3, start:0.65, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ fontSize:56, fontWeight:500, fontStyle:"italic",
          fontFamily:"'Playfair Display', serif",
          color:"#ffffff", textAlign:"left", lineHeight:1.3,
          background:"rgba(255,255,255,0.07)", borderRadius:10 } },
      { id:"z8", type:"text", role:"subtext", maxChars:50, order:5, x:4, y:70, width:92, height:20, zIndex:3, start:0.8, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:600, color:"#ffffff", textAlign:"center",
          lineHeight:1.25, textShadow:"0 2px 12px rgba(0,0,0,0.8)" } },
    ],
  },

];