/**
 * layouts/proof/index.js
 * Structurally distinct PROOF layouts.
 *
 * Proof = evidence, credibility, results, social proof, data.
 * Show don't tell. Numbers, faces, lists, collages.
 * Single primary intent per layout.
 * Font sizes calibrated for 1080×1920 canvas.
 */

export default [

  // 1 — Asset top + stacked list below
  {
    id: "AssetWithList", label: "Asset With List",
    intent: ["proof"],
    energy: ["medium"], orientation: ["9:16"],
    niche: ["education", "finance", "health", "lifestyle", "entertainment"],
    assetCount: 1, textCount: 4, captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:0, y:0, width:100, height:40, zIndex:1, start:0, end:null,
        enterAnimation:"scaleIn", exitAnimation:"none",
        style:{ objectFit:"cover" } },
      { id:"z2", type:"text", role:"headline", maxChars:28, order:1, x:5, y:42, width:90, height:13, zIndex:2, start:0.2, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:104, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"left", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      { id:"z3", type:"text", role:"subtext", maxChars:40, order:2, x:5, y:57, width:90, height:11, zIndex:2, start:0.4, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:68, fontWeight:700, color:"#ffffff", textAlign:"left", lineHeight:1.1 } },
      { id:"z4", type:"text", role:"subtext", maxChars:40, order:3, x:5, y:70, width:90, height:11, zIndex:2, start:0.6, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:68, fontWeight:700, color:"#ffffff", textAlign:"left", lineHeight:1.1 } },
      { id:"z5", type:"text", role:"subtext", maxChars:40, order:4, x:5, y:83, width:90, height:11, zIndex:2, start:0.8, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:600, color:"#ffffff", textAlign:"left", lineHeight:1.1, opacity:0.85 } },
    ],
  },

  // 2 — Side by side: asset left + text stack right
  {
    id: "SideBySide", label: "Side By Side",
    intent: ["proof"],
    energy: ["medium"], orientation: ["9:16"],
    niche: ["education", "health", "finance", "lifestyle", "tech"],
    assetCount: 1, textCount: 3, captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:0, y:14, width:48, height:66, zIndex:1, start:0, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:16 } },
      { id:"z2", type:"text", role:"headline", maxChars:22, order:1, x:52, y:16, width:46, height:30, zIndex:2, start:0.3, end:null,
        enterAnimation:"slideLeftIn", exitAnimation:"none",
        style:{ fontSize:108, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"left", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      { id:"z3", type:"text", role:"subtext", maxChars:45, order:2, x:52, y:50, width:46, height:20, zIndex:2, start:0.5, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:500, color:"#ffffff", textAlign:"left",
          lineHeight:1.4, opacity:0.9 } },
      { id:"z4", type:"text", role:"label", maxChars:18, order:3, x:52, y:72, width:46, height:10, zIndex:2, start:0.7, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:400, fontStyle:"italic",
          fontFamily:"'Playfair Display', serif",
          color:"#ffffff", textAlign:"left", opacity:0.65 } },
    ],
  },

  // 3 — Four-grid collage + title header
  {
    id: "FourCollage", label: "Four Collage",
    intent: ["proof"],
    energy: ["medium", "high"], orientation: ["9:16"],
    niche: ["entertainment", "lifestyle", "travel", "food", "sports"],
    assetCount: 4, textCount: 1, captionStrategy: "never",
    zones: [
      { id:"z1", type:"text", role:"headline", maxChars:28, order:1, x:5, y:2, width:90, height:12, zIndex:4, start:0, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ fontSize:104, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      { id:"z2", type:"asset", role:"primary_asset", order:1, x:1, y:15, width:48, height:38, zIndex:2, start:0.2, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:12 } },
      { id:"z3", type:"asset", role:"secondary_asset", order:2, x:51, y:15, width:48, height:38, zIndex:2, start:0.35, end:null,
        enterAnimation:"slideLeftIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:12 } },
      { id:"z4", type:"asset", role:"asset_3", order:3, x:1, y:54, width:48, height:38, zIndex:2, start:0.5, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:12 } },
      { id:"z5", type:"asset", role:"asset_4", order:4, x:51, y:54, width:48, height:38, zIndex:2, start:0.65, end:null,
        enterAnimation:"slideLeftIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:12 } },
    ],
  },

  // 4 — Data rows: headline + labeled rows with subtle bg
  {
    id: "DataRowsProof", label: "Data Rows",
    intent: ["proof"],
    energy: ["low", "medium"], orientation: ["9:16"],
    niche: ["finance", "tech", "education", "health"],
    assetCount: 0, textCount: 5, captionStrategy: "never",
    zones: [
      { id:"z1", type:"text", role:"headline", maxChars:28, order:1, x:4, y:4, width:92, height:13, zIndex:2, start:0, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ fontSize:104, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"left", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      { id:"z2", type:"text", role:"subtext", maxChars:40, order:2, x:4, y:21, width:92, height:12, zIndex:2, start:0.25, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:68, fontWeight:700, color:"#ffffff", textAlign:"left",
          background:"rgba(255,255,255,0.08)", borderRadius:8, lineHeight:1.1 } },
      { id:"z3", type:"text", role:"subtext", maxChars:40, order:3, x:4, y:36, width:92, height:12, zIndex:2, start:0.45, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:68, fontWeight:700, color:"#ffffff", textAlign:"left",
          background:"rgba(255,255,255,0.08)", borderRadius:8, lineHeight:1.1 } },
      { id:"z4", type:"text", role:"subtext", maxChars:40, order:4, x:4, y:51, width:92, height:12, zIndex:2, start:0.65, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:68, fontWeight:700, color:"#ffffff", textAlign:"left",
          background:"rgba(255,255,255,0.08)", borderRadius:8, lineHeight:1.1 } },
      { id:"z5", type:"text", role:"subtext", maxChars:40, order:5, x:4, y:66, width:92, height:12, zIndex:2, start:0.82, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:68, fontWeight:700, color:"#ffffff", textAlign:"left",
          background:"rgba(255,255,255,0.08)", borderRadius:8, lineHeight:1.1 } },
    ],
  },

  // 5 — Stat proof: giant number + context label + asset background
  {
    id: "StatProof", label: "Stat Proof",
    intent: ["proof"],
    energy: ["high", "medium"], orientation: ["9:16"],
    niche: ["finance", "health", "sports", "education", "tech"],
    assetCount: 1, textCount: 3, captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:0, y:0, width:100, height:100, zIndex:1, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:0 } },
      { id:"z2", type:"decorative", role:"decorative", order:1, x:0, y:0, width:100, height:100, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ background:"linear-gradient(180deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.85) 100%)",
          opacity:1, borderRadius:0 } },
      { id:"z3", type:"text", role:"label", maxChars:22, order:1, x:4, y:6, width:92, height:8, zIndex:3, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:600, color:"#ffffff", textAlign:"center",
          letterSpacing:"0.15em", opacity:0.65, textTransform:"uppercase" } },
      { id:"z4", type:"text", role:"stat", maxChars:8, order:2, x:2, y:28, width:96, height:36, zIndex:3, start:0.3, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:240, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.9,
          textShadow:"0 8px 48px rgba(0,0,0,0.95)" } },
      { id:"z5", type:"text", role:"subtext", maxChars:50, order:3, x:4, y:72, width:92, height:20, zIndex:3, start:0.6, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:68, fontWeight:700, color:"#ffffff", textAlign:"center",
          lineHeight:1.25, textShadow:"0 2px 16px rgba(0,0,0,0.9)" } },
    ],
  },

  // 6 — Review card: oval asset + star icons + quote + name/handle
  {
    id: "ReviewCardProof", label: "Review Card Proof",
    intent: ["proof"],
    energy: ["low", "medium"], orientation: ["9:16"],
    niche: ["lifestyle", "health", "food", "education", "finance"],
    assetCount: 1, textCount: 3, captionStrategy: "never",
    zones: [
      { id:"z1", type:"text", role:"label", maxChars:20, order:1, x:4, y:3, width:92, height:9, zIndex:3, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:56, fontWeight:700, color:"#ffffff", textAlign:"center",
          letterSpacing:"0.08em", opacity:0.7, textTransform:"uppercase" } },
      { id:"z2", type:"asset", role:"primary_asset", order:1, x:30, y:14, width:40, height:26, zIndex:2, start:0.2, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:999 } },
      { id:"z3", type:"decorative", role:"decorative", order:1, x:26, y:12, width:48, height:30, zIndex:3, start:0.2, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ borderRadius:999, opacity:1 } },
      { id:"z4", type:"icon", role:"icon", order:1, x:28, y:44, width:44, height:10, zIndex:3, start:0.3, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        iconify:{ set:"ph", icon:"star-fill" },
        style:{ opacity:1 } },
      { id:"z5", type:"text", role:"quote", maxChars:80, order:2, x:5, y:57, width:90, height:28, zIndex:3, start:0.4, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:400, fontStyle:"italic",
          fontFamily:"'Playfair Display', serif",
          color:"#ffffff", textAlign:"center", lineHeight:1.4,
          textShadow:"0 2px 8px rgba(0,0,0,0.6)" } },
      { id:"z6", type:"text", role:"tagline", maxChars:22, order:3, x:5, y:87, width:90, height:9, zIndex:3, start:0.7, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:600, color:"#ffffff", textAlign:"center",
          opacity:0.7, letterSpacing:"0.08em" } },
    ],
  },

  // 7 — Three stat columns: icon + number + label per column
  {
    id: "ThreeStatProof", label: "Three Stat Proof",
    intent: ["proof"],
    energy: ["medium", "high"], orientation: ["9:16"],
    niche: ["finance", "health", "sports", "education", "tech"],
    assetCount: 0, textCount: 7, captionStrategy: "never",
    zones: [
      { id:"z1", type:"text", role:"headline", maxChars:24, order:1, x:4, y:3, width:92, height:12, zIndex:3, start:0, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ fontSize:104, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      // Col 1
      { id:"z2", type:"icon", role:"icon", order:1, x:4, y:20, width:28, height:16, zIndex:3, start:0.2, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        iconify:{ set:"ph", icon:"users-fill" },
        style:{ opacity:1 } },
      { id:"z3", type:"text", role:"stat", maxChars:8, order:2, x:4, y:38, width:28, height:14, zIndex:3, start:0.3, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:112, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:1.0 } },
      { id:"z4", type:"text", role:"label", maxChars:12, order:3, x:4, y:54, width:28, height:8, zIndex:3, start:0.35, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:600, color:"#ffffff", textAlign:"center",
          lineHeight:1.0, opacity:0.7 } },
      // Col 2
      { id:"z5", type:"icon", role:"icon", order:2, x:36, y:20, width:28, height:16, zIndex:3, start:0.4, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        iconify:{ set:"ph", icon:"chart-bar-fill" },
        style:{ opacity:1 } },
      { id:"z6", type:"text", role:"stat", maxChars:8, order:4, x:36, y:38, width:28, height:14, zIndex:3, start:0.5, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:112, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:1.0 } },
      { id:"z7", type:"text", role:"label", maxChars:12, order:5, x:36, y:54, width:28, height:8, zIndex:3, start:0.55, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:600, color:"#ffffff", textAlign:"center",
          lineHeight:1.0, opacity:0.7 } },
      // Col 3
      { id:"z8", type:"icon", role:"icon", order:3, x:68, y:20, width:28, height:16, zIndex:3, start:0.6, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        iconify:{ set:"ph", icon:"trophy-fill" },
        style:{ opacity:1 } },
      { id:"z9", type:"text", role:"stat", maxChars:8, order:6, x:68, y:38, width:28, height:14, zIndex:3, start:0.7, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:112, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:1.0 } },
      { id:"z10", type:"text", role:"label", maxChars:12, order:7, x:68, y:54, width:28, height:8, zIndex:3, start:0.75, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:600, color:"#ffffff", textAlign:"center",
          lineHeight:1.0, opacity:0.7 } },
      { id:"z11", type:"text", role:"subtext", maxChars:55, order:8, x:4, y:70, width:92, height:20, zIndex:3, start:0.88, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:600, color:"#ffffff", textAlign:"center",
          lineHeight:1.25, textShadow:"0 2px 12px rgba(0,0,0,0.8)" } },
    ],
  },

  // 8 — Picture in picture: large asset + small inset asset + proof text
  {
    id: "PictureInPictureProof", label: "Picture In Picture Proof",
    intent: ["proof"],
    energy: ["medium", "high"], orientation: ["9:16"],
    niche: ["entertainment", "sports", "lifestyle", "gaming", "education"],
    assetCount: 2, textCount: 2, captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:0, y:0, width:100, height:70, zIndex:1, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:0 } },
      { id:"z2", type:"asset", role:"secondary_asset", order:2, x:60, y:48, width:36, height:26, zIndex:3, start:0.3, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:12,
          outline:"6px solid #ffffff", outlineOffset:"-6px" } },
      { id:"z3", type:"text", role:"headline", maxChars:26, order:1, x:4, y:72, width:92, height:14, zIndex:3, start:0.4, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:108, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"left", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      { id:"z4", type:"text", role:"subtext", maxChars:50, order:2, x:4, y:88, width:92, height:10, zIndex:3, start:0.6, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:500, color:"#ffffff", textAlign:"left",
          lineHeight:1.3, opacity:0.85 } },
    ],
  },

  // 9 — Check list proof: headline + 4 check items with icons
  {
    id: "CheckListProof", label: "Check List Proof",
    intent: ["proof"],
    energy: ["medium"], orientation: ["9:16"],
    niche: ["education", "health", "finance", "lifestyle", "tech"],
    assetCount: 0, textCount: 5, captionStrategy: "never",
    zones: [
      { id:"z1", type:"text", role:"headline", maxChars:24, order:1, x:4, y:4, width:92, height:13, zIndex:3, start:0, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ fontSize:104, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"left", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      { id:"z2", type:"decorative", role:"decorative", order:1, x:4, y:19, width:92, height:1, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ opacity:0.25, borderRadius:2 } },
      // Item 1
      { id:"z3", type:"icon", role:"icon", order:1, x:4, y:23, width:12, height:10, zIndex:4, start:0.2, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        iconify:{ set:"ph", icon:"check-circle-fill" },
        style:{ opacity:1 } },
      { id:"z4", type:"text", role:"subtext", maxChars:38, order:2, x:19, y:24, width:77, height:8, zIndex:3, start:0.25, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:700, color:"#ffffff", textAlign:"left", lineHeight:1.1 } },
      // Item 2
      { id:"z5", type:"icon", role:"icon", order:2, x:4, y:36, width:12, height:10, zIndex:4, start:0.4, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        iconify:{ set:"ph", icon:"check-circle-fill" },
        style:{ opacity:1 } },
      { id:"z6", type:"text", role:"subtext", maxChars:38, order:3, x:19, y:37, width:77, height:8, zIndex:3, start:0.45, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:700, color:"#ffffff", textAlign:"left", lineHeight:1.1 } },
      // Item 3
      { id:"z7", type:"icon", role:"icon", order:3, x:4, y:49, width:12, height:10, zIndex:4, start:0.6, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        iconify:{ set:"ph", icon:"check-circle-fill" },
        style:{ opacity:1 } },
      { id:"z8", type:"text", role:"subtext", maxChars:38, order:4, x:19, y:50, width:77, height:8, zIndex:3, start:0.65, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:700, color:"#ffffff", textAlign:"left", lineHeight:1.1 } },
      // Item 4
      { id:"z9", type:"icon", role:"icon", order:4, x:4, y:62, width:12, height:10, zIndex:4, start:0.78, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        iconify:{ set:"ph", icon:"check-circle-fill" },
        style:{ opacity:1 } },
      { id:"z10", type:"text", role:"subtext", maxChars:38, order:5, x:19, y:63, width:77, height:8, zIndex:3, start:0.82, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:700, color:"#ffffff", textAlign:"left", lineHeight:1.1 } },
      { id:"z11", type:"text", role:"label", maxChars:40, order:6, x:4, y:78, width:92, height:12, zIndex:3, start:0.93, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:600, color:"#ffffff", textAlign:"center",
          background:"rgba(255,255,255,0.1)", borderRadius:10,
          lineHeight:1.2, letterSpacing:"0.05em" } },
    ],
  },

];