/**
 * layouts/escalate/index.js
 * Structurally distinct ESCALATE layouts.
 *
 * Escalate = building tension, stacking evidence, things piling up visually.
 * Energetic, sequential, momentum-driven.
 * Single primary intent per layout.
 * Font sizes calibrated for 1080×1920 canvas.
 */

export default [

  // 1 — Building list: stacked items sliding up over full-bleed asset
  {
    id: "BuildingList",
    label: "Building List",
    intent: ["escalate"],
    energy: ["medium", "high"],
    orientation: ["9:16"],
    niche: ["education", "finance", "health", "lifestyle", "entertainment"],
    assetCount: 1, textCount: 4,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:0, y:0, width:100, height:100, zIndex:1, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ objectFit:"cover" } },
      { id:"z2", type:"decorative", role:"decorative", order:1, x:0, y:0, width:100, height:100, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ background:"linear-gradient(180deg, rgba(0,0,0,0.6) 0%, rgba(0,0,0,0.85) 100%)",
          opacity:1, borderRadius:0 } },
      { id:"z3", type:"text", role:"headline", maxChars:25, order:1, x:5, y:6, width:90, height:13, zIndex:3, start:0, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ fontSize:108, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      { id:"z4", type:"text", role:"subtext", maxChars:38, order:2, x:5, y:26, width:90, height:13, zIndex:3, start:0.3, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:68, fontWeight:700, color:"#ffffff", textAlign:"left",
          background:"rgba(0,0,0,0.55)", borderRadius:10, lineHeight:1.1,
          paddingLeft:12, paddingRight:12 } },
      { id:"z5", type:"text", role:"subtext", maxChars:38, order:3, x:5, y:42, width:90, height:13, zIndex:3, start:0.55, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:68, fontWeight:700, color:"#ffffff", textAlign:"left",
          background:"rgba(0,0,0,0.55)", borderRadius:10, lineHeight:1.1,
          paddingLeft:12, paddingRight:12 } },
      { id:"z6", type:"text", role:"subtext", maxChars:38, order:4, x:5, y:58, width:90, height:13, zIndex:3, start:0.8, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:68, fontWeight:700, color:"#ffffff", textAlign:"left",
          background:"rgba(0,0,0,0.55)", borderRadius:10, lineHeight:1.1,
          paddingLeft:12, paddingRight:12 } },
    ],
  },

  // 2 — Title full-width + asset reveal below + subtext
  {
    id: "TitleThenAsset",
    label: "Title Then Asset",
    intent: ["escalate"],
    energy: ["high", "medium"],
    orientation: ["9:16"],
    niche: ["entertainment", "education", "sports", "gaming", "finance"],
    assetCount: 1, textCount: 2,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"text", role:"headline", maxChars:28, order:1, x:4, y:5, width:92, height:14, zIndex:3, start:0, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ fontSize:112, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.95,
          letterSpacing:"-1px", textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      { id:"z2", type:"asset", role:"primary_asset", order:1, x:3, y:22, width:94, height:58, zIndex:1, start:0.4, end:null,
        enterAnimation:"scaleIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:16 } },
      { id:"z3", type:"text", role:"subtext", maxChars:40, order:2, x:4, y:83, width:92, height:12, zIndex:3, start:0.7, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:600, color:"#ffffff", textAlign:"center",
          lineHeight:1.2, textShadow:"0 2px 12px rgba(0,0,0,0.8)" } },
    ],
  },

  // 3 — Numbered countdown: 3 large numbers stacking with text beside each
  {
    id: "NumberedEscalate",
    label: "Numbered Escalate",
    intent: ["escalate"],
    energy: ["high"],
    orientation: ["9:16"],
    niche: ["education", "finance", "health", "lifestyle", "entertainment"],
    assetCount: 0, textCount: 7,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"text", role:"headline", maxChars:24, order:1, x:4, y:3, width:92, height:11, zIndex:3, start:0, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ fontSize:96, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      // Row 1
      { id:"z2", type:"text", role:"stat", maxChars:2, order:2, x:4, y:18, width:18, height:16, zIndex:3, start:0.2, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:140, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:1.0, opacity:0.9 } },
      { id:"z3", type:"text", role:"subtext", maxChars:35, order:3, x:25, y:20, width:70, height:12, zIndex:3, start:0.25, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:700, color:"#ffffff", textAlign:"left",
          lineHeight:1.15, textShadow:"0 2px 8px rgba(0,0,0,0.8)" } },
      // Row 2
      { id:"z4", type:"text", role:"stat", maxChars:2, order:4, x:4, y:38, width:18, height:16, zIndex:3, start:0.45, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:140, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:1.0, opacity:0.9 } },
      { id:"z5", type:"text", role:"subtext", maxChars:35, order:5, x:25, y:40, width:70, height:12, zIndex:3, start:0.5, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:700, color:"#ffffff", textAlign:"left",
          lineHeight:1.15, textShadow:"0 2px 8px rgba(0,0,0,0.8)" } },
      // Row 3
      { id:"z6", type:"text", role:"stat", maxChars:2, order:6, x:4, y:58, width:18, height:16, zIndex:3, start:0.7, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:140, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:1.0, opacity:0.9 } },
      { id:"z7", type:"text", role:"subtext", maxChars:35, order:7, x:25, y:60, width:70, height:12, zIndex:3, start:0.75, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:700, color:"#ffffff", textAlign:"left",
          lineHeight:1.15, textShadow:"0 2px 8px rgba(0,0,0,0.8)" } },
      // Bottom payoff
      { id:"z8", type:"text", role:"label", maxChars:40, order:8, x:4, y:80, width:92, height:12, zIndex:3, start:0.9, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:600, color:"#ffffff", textAlign:"center",
          background:"rgba(255,255,255,0.12)", borderRadius:10,
          lineHeight:1.2, letterSpacing:"0.05em" } },
    ],
  },

  // 4 — Asset top + escalating text blocks bottom with growing size
  {
    id: "GrowingTextEscalate",
    label: "Growing Text Escalate",
    intent: ["escalate"],
    energy: ["high"],
    orientation: ["9:16"],
    niche: ["entertainment", "sports", "gaming", "finance"],
    assetCount: 1, textCount: 4,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:0, y:0, width:100, height:46, zIndex:1, start:0, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:0 } },
      { id:"z2", type:"text", role:"label", maxChars:20, order:1, x:4, y:48, width:92, height:8, zIndex:3, start:0.2, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:600, color:"#ffffff", textAlign:"center",
          letterSpacing:"0.12em", opacity:0.6, textTransform:"uppercase" } },
      { id:"z3", type:"text", role:"subtext", maxChars:30, order:2, x:4, y:57, width:92, height:10, zIndex:3, start:0.35, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:80, fontWeight:700, color:"#ffffff", textAlign:"center",
          lineHeight:1.0, textShadow:"0 2px 12px rgba(0,0,0,0.8)" } },
      { id:"z4", type:"text", role:"headline", maxChars:22, order:3, x:2, y:68, width:96, height:14, zIndex:3, start:0.6, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:128, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.95,
          textShadow:"0 4px 28px rgba(0,0,0,0.95)" } },
      { id:"z5", type:"text", role:"stat", maxChars:10, order:4, x:2, y:83, width:96, height:14, zIndex:3, start:0.85, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:148, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.9,
          textShadow:"0 6px 36px rgba(0,0,0,0.95)" } },
    ],
  },

  // 5 — Three asset mosaic stacking in + headline overlay
  {
    id: "MosaicEscalate",
    label: "Mosaic Escalate",
    intent: ["escalate"],
    energy: ["high"],
    orientation: ["9:16"],
    niche: ["entertainment", "lifestyle", "travel", "food", "sports"],
    assetCount: 3, textCount: 2,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:0, y:0, width:100, height:42, zIndex:1, start:0, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:0 } },
      { id:"z2", type:"asset", role:"secondary_asset", order:2, x:0, y:44, width:49, height:38, zIndex:1, start:0.25, end:null,
        enterAnimation:"slideRightIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:0 } },
      { id:"z3", type:"asset", role:"asset_3", order:3, x:51, y:44, width:49, height:38, zIndex:1, start:0.45, end:null,
        enterAnimation:"slideLeftIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:0 } },
      { id:"z4", type:"text", role:"headline", maxChars:24, order:1, x:3, y:83, width:94, height:13, zIndex:3, start:0.65, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:108, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.95,
          textShadow:"0 4px 28px rgba(0,0,0,0.95)" } },
      { id:"z5", type:"text", role:"label", maxChars:20, order:2, x:3, y:20, width:60, height:8, zIndex:3, start:0.1, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:700, color:"#ffffff", textAlign:"left",
          background:"rgba(0,0,0,0.6)", borderRadius:6,
          letterSpacing:"0.08em", lineHeight:1.0 } },
    ],
  },

  // 6 — Icon grid escalate: 4 icons appearing one by one + headline bottom
  {
    id: "IconGridEscalate",
    label: "Icon Grid Escalate",
    intent: ["escalate"],
    energy: ["medium", "high"],
    orientation: ["9:16"],
    niche: ["education", "finance", "health", "tech", "lifestyle"],
    assetCount: 0, textCount: 3,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"text", role:"label", maxChars:20, order:1, x:4, y:4, width:92, height:8, zIndex:3, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:600, color:"#ffffff", textAlign:"center",
          letterSpacing:"0.15em", opacity:0.65, textTransform:"uppercase" } },
      { id:"z2", type:"icon", role:"icon", order:1, x:12, y:16, width:32, height:22, zIndex:3, start:0.15, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        iconify:{ set:"ph", icon:"number-circle-one-fill" },
        style:{ opacity:1 } },
      { id:"z3", type:"icon", role:"icon", order:2, x:56, y:16, width:32, height:22, zIndex:3, start:0.3, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        iconify:{ set:"ph", icon:"number-circle-two-fill" },
        style:{ opacity:1 } },
      { id:"z4", type:"icon", role:"icon", order:3, x:12, y:42, width:32, height:22, zIndex:3, start:0.5, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        iconify:{ set:"ph", icon:"number-circle-three-fill" },
        style:{ opacity:1 } },
      { id:"z5", type:"icon", role:"icon", order:4, x:56, y:42, width:32, height:22, zIndex:3, start:0.7, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        iconify:{ set:"ph", icon:"number-circle-four-fill" },
        style:{ opacity:1 } },
      { id:"z6", type:"text", role:"headline", maxChars:28, order:2, x:3, y:70, width:94, height:16, zIndex:3, start:0.85, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:112, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.95,
          textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      { id:"z7", type:"text", role:"subtext", maxChars:45, order:3, x:4, y:88, width:92, height:10, zIndex:3, start:0.95, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:60, fontWeight:600, color:"#ffffff", textAlign:"center",
          lineHeight:1.2, opacity:0.85 } },
    ],
  },

  // 7 — Split asset + escalating stat reveal
  {
    id: "StatRevealEscalate",
    label: "Stat Reveal Escalate",
    intent: ["escalate"],
    energy: ["high"],
    orientation: ["9:16"],
    niche: ["finance", "sports", "education", "health", "tech"],
    assetCount: 1, textCount: 4,
    captionStrategy: "never",
    zones: [
      { id:"z1", type:"asset", role:"primary_asset", order:1, x:0, y:0, width:100, height:52, zIndex:1, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ objectFit:"cover", borderRadius:0 } },
      { id:"z2", type:"decorative", role:"decorative", order:1, x:0, y:40, width:100, height:20, zIndex:2, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ background:"linear-gradient(0deg, rgba(0,0,0,1) 0%, transparent 100%)",
          opacity:1, borderRadius:0 } },
      { id:"z3", type:"text", role:"label", maxChars:20, order:1, x:4, y:54, width:92, height:8, zIndex:3, start:0.3, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:600, color:"#ffffff", textAlign:"center",
          letterSpacing:"0.12em", opacity:0.65, textTransform:"uppercase" } },
      { id:"z4", type:"text", role:"stat", maxChars:8, order:2, x:2, y:62, width:96, height:22, zIndex:3, start:0.5, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:200, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.9,
          textShadow:"0 8px 48px rgba(0,0,0,0.95)" } },
      { id:"z5", type:"text", role:"subtext", maxChars:40, order:3, x:4, y:86, width:92, height:12, zIndex:3, start:0.75, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:64, fontWeight:700, color:"#ffffff", textAlign:"center",
          lineHeight:1.2, textShadow:"0 2px 12px rgba(0,0,0,0.8)" } },
    ],
  },

  // 8 — Full text escalation: label → subtext → headline growing in size, no asset
  {
    id: "PureTextEscalate",
    label: "Pure Text Escalate",
    intent: ["escalate"],
    energy: ["high", "medium"],
    orientation: ["9:16"],
    niche: ["entertainment", "education", "finance", "gaming", "health"],
    assetCount: 0, textCount: 4,
    captionStrategy: "always",
    zones: [
      { id:"z1", type:"text", role:"label", maxChars:20, order:1, x:5, y:8, width:90, height:8, zIndex:3, start:0, end:null,
        enterAnimation:"fadeIn", exitAnimation:"none",
        style:{ fontSize:52, fontWeight:500, color:"#ffffff", textAlign:"center",
          letterSpacing:"0.2em", opacity:0.55, textTransform:"uppercase" } },
      { id:"z2", type:"text", role:"tagline", maxChars:30, order:2, x:5, y:22, width:90, height:14, zIndex:3, start:0.25, end:null,
        enterAnimation:"slideDownIn", exitAnimation:"none",
        style:{ fontSize:84, fontWeight:700, color:"#ffffff", textAlign:"center",
          lineHeight:1.05, opacity:0.75,
          textShadow:"0 2px 16px rgba(0,0,0,0.8)" } },
      { id:"z3", type:"text", role:"subtext", maxChars:28, order:3, x:3, y:40, width:94, height:18, zIndex:3, start:0.5, end:null,
        enterAnimation:"slideUpIn", exitAnimation:"none",
        style:{ fontSize:120, fontWeight:800, color:"#ffffff", textAlign:"center",
          lineHeight:1.0, textShadow:"0 4px 24px rgba(0,0,0,0.9)" } },
      { id:"z4", type:"text", role:"headline", maxChars:20, order:4, x:2, y:62, width:96, height:26, zIndex:3, start:0.75, end:null,
        enterAnimation:"popIn", exitAnimation:"none",
        style:{ fontSize:172, fontWeight:900, fontFamily:"'Bebas Neue', sans-serif",
          color:"#ffffff", textAlign:"center", lineHeight:0.9,
          textShadow:"0 6px 40px rgba(0,0,0,0.95)" } },
    ],
  },

];